package com.jeiker.xblog.model;

public class Oauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth.created_at
     *
     * @mbggenerated
     */
    private Double createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth.id
     *
     * @return the value of oauth.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth.id
     *
     * @param id the value for oauth.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth.user_id
     *
     * @return the value of oauth.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth.user_id
     *
     * @param userId the value for oauth.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth.created_at
     *
     * @return the value of oauth.created_at
     *
     * @mbggenerated
     */
    public Double getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth.created_at
     *
     * @param createdAt the value for oauth.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Double createdAt) {
        this.createdAt = createdAt;
    }
}