package com.jeiker.xblog.dao;

import com.jeiker.xblog.model.Oauth;
import com.jeiker.xblog.model.OauthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int countByExample(OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int deleteByExample(OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int insert(Oauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int insertSelective(Oauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    List<Oauth> selectByExample(OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    Oauth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Oauth record, @Param("example") OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Oauth record, @Param("example") OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Oauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Oauth record);
}